### ISSUE TITLE
[feature request] Stats in separate panel area

### ISSUE THREAD

**Issue by ieteo** [sylvainjule/kirby-matomo#39]
Hi,

Would it be possible to move the stats onto separate panel area? 

The rational behind having the matomo stats in separate panel area, is to declutter the site page in panel.

I looked into implementing it myself, but got lost midway through. According to Kirby Team, this is apparently an easy task.  Would you possibly consider it please.

Thank you

**Comment by Orsim27** [comment]
Hey,

I personally just used [tabs](https://getkirby.com/docs/guide/blueprints/tabs) for that, so in my site.yml I have:

```
tabs:
  pages:
    preset: pages
    unlisted: true
  matomo:
    columns:
      - width: 3/4
        sections:
          main:
            type: matomo-main
      - width: 1/4
        sections:
          sidebar:
            type: matomo-sidebar
```

Then you have different tabs, one for your default site view (all pages and stuff) and a second one with the matomo view
