### ISSUE TITLE
Page widget does not seem to show any existing tracking data

### ISSUE THREAD

**Issue by plagasul** [sylvainjule/kirby-matomo#44]
Hello,

I have this fantastic plugin in a Kirby 3.7.2.1 installation

I have the dashboard in a tab in site.yml, fully working, like this:

```
  analytics:
    icon: chart
    columns:
      - width: 3/4
        sections:
          main:
            type: matomo-main
      - width: 1/4
        sections:
          sidebar:
            type: matomo-sidebar      
```

It shows data, and this data seems to match the one that I see at Matomo's own dashboard. 

I also have a widget in a type of page, like this:

```
    sections:
      matomo:
        type: matomo-page
        period: year
        overview: true
```

Both this type of page and its parent are always unlisted (not draft)

Matomo records visits to these pages, but not the widget:

![image](https://github.com/sylvainjule/kirby-matomo/assets/13966673/2c94247e-d3ef-4960-9272-edbd7a55ef2b)

Config options:
```
    'sylvainjule.matomo.url' => 'https://xxxxxxxx.com/matomo',
    'sylvainjule.matomo.id' => '3',
    'sylvainjule.matomo.token' => 'xxxxxxxxxxxxxxxxxxxxx',
    'sylvainjule.matomo.active' => true,
    'sylvainjule.matomo.disableCookies' => true,
```

As you see I use cookie-less Matomo.

I have no routes in config.

How to troubleshoot this?

Thanks
